# Your personal GitHub token
github_token: 3b0353f6e49675981145e1fa1cc2d9cf4aeb6658

# Guest OS timezone
timezone: Europe/London

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: web

# Virtual machine IP
ip: 192.168.83.180

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 1024